#include "Utility/MovieLimits.h"

const int MIN_ACTORS_YEAR_OF_BIRTH = 1888;
const int MAX_ACTORS_YEAR_OF_BIRTH = 2018;

const int MIN_MOVIES_RELEASE_YEAR = 1888;
const int MAX_MOVIES_RELEASE_YEAR = 2018;
const int MIN_MOVIES_RUNNING_TIME = 1;
const int MAX_MOVIES_RUNNING_TIME = 14400;

const int MIN_STUDIOS_YEAR_OF_FOUNDING = 1888;
const int MAX_STUDIOS_YEAR_OF_FOUNDING = 2018;
